jdk:
  - oraclejdk8
script: mvn package
before_deploy:
 - "mkdir build"
 - "cp ./target/ShareMyWeek-*.jar ./build/ShareMyWeek.jar"
 - "git checkout -b deploy"
 - "git add ."
 - "git config user.email $DEPLOY_USER"
 - "git config user.name $DEPLOY_DOMAIN"
 - "git commit --amend --no-edit"
deploy:
  provider: $DEPLOY_PROVIDER
  user: $DEPLOY_USER
  password: $DEPLOY_PASSWORD
  domain: $DEPLOY_DOMAIN
  app: $DEPLOY_APP
  skip_cleanup: true
  on: deploy