jdk:
  - oraclejdk8
script: mvn package
before_deploy: "cp ./target/ShareMyWeek-*.jar ./build"
deploy:
  provider: $DEPLOY_PROVIDER
  user: $DEPLOY_USER
  password: $DEPLOY_PASSWORD
  domain: $DEPLOY_DOMAIN
  app: $DEPLOY_APP
  skip_cleanup: true